import AppKit
import Carbon.HIToolbox

/// Puts text into whatever text field has keyboard focus by writing it to the clipboard and
/// synthesizing ⌘V, then restores the previous clipboard.
@MainActor
final class Paster {
    enum Outcome: Equatable {
        case pasted
        case copiedOnly(reason: String)
    }

    /// Tags synthetic key events so Utter's own event handling can recognize them.
    static let eventTag: Int64 = 0x5554_5452  // "UTTR"

    private var restoreTask: Task<Void, Never>?

    func deliver(_ text: String, autoPaste: Bool, restoreClipboard: Bool) async -> Outcome {
        let pasteboard = NSPasteboard.general
        // A restore still pending from the previous dictation would clobber this one.
        restoreTask?.cancel()
        restoreTask = nil

        guard autoPaste else {
            write(text, to: pasteboard)
            return .copiedOnly(reason: "auto-paste is off")
        }
        guard Permissions.canPostEvents else {
            write(text, to: pasteboard)
            return .copiedOnly(reason: "allow Utter under Accessibility to paste automatically")
        }

        let snapshot = restoreClipboard ? Self.snapshot(pasteboard) : nil
        write(text, to: pasteboard)
        let ourChangeCount = pasteboard.changeCount

        try? await Task.sleep(for: .milliseconds(60))
        Self.postCommandV()

        if let snapshot {
            restoreTask = Task {
                // Slow targets (Electron, remote desktops) read the clipboard lazily after ⌘V.
                try? await Task.sleep(for: .milliseconds(1_200))
                guard !Task.isCancelled, pasteboard.changeCount == ourChangeCount else { return }
                Self.restore(snapshot, to: pasteboard)
            }
        }
        return .pasted
    }

    func copy(_ text: String) {
        write(text, to: NSPasteboard.general, transient: false)
    }

    private func write(_ text: String, to pasteboard: NSPasteboard, transient: Bool = true) {
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        if transient {
            // nspasteboard.org markers: clipboard managers skip transient, auto-generated content.
            item.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType"))
            item.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))
        }
        item.setString(
            Bundle.main.bundleIdentifier ?? "com.milescs.utter",
            forType: NSPasteboard.PasteboardType("org.nspasteboard.source")
        )
        pasteboard.writeObjects([item])
    }

    private typealias Snapshot = [[NSPasteboard.PasteboardType: Data]]

    private static func snapshot(_ pasteboard: NSPasteboard) -> Snapshot? {
        // Reading is what macOS's (not yet enforced) pasteboard privacy prompt guards; don't trigger it.
        switch pasteboard.accessBehavior {
        case .ask, .alwaysDeny: return nil
        default: break
        }
        return (pasteboard.pasteboardItems ?? []).map { item in
            var entry: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types {
                if let data = item.data(forType: type) { entry[type] = data }
            }
            return entry
        }
    }

    private static func restore(_ snapshot: Snapshot, to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        let items = snapshot.compactMap { entry -> NSPasteboardItem? in
            guard !entry.isEmpty else { return nil }
            let item = NSPasteboardItem()
            for (type, data) in entry { item.setData(data, forType: type) }
            return item
        }
        if !items.isEmpty { pasteboard.writeObjects(items) }
    }

    private static func postCommandV() {
        let source = CGEventSource(stateID: .combinedSessionState)
        let key = keyCodeForV()
        for isDown in [true, false] {
            guard let event = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: isDown) else { continue }
            event.flags = .maskCommand
            event.setIntegerValueField(.eventSourceUserData, value: eventTag)
            event.post(tap: .cghidEventTap)
        }
    }

    /// The key that produces "v" in the current layout, so ⌘V works on Dvorak/AZERTY; falls back to the
    /// ANSI V position for "QWERTY ⌘" layouts and non-Latin layouts.
    private static func keyCodeForV() -> CGKeyCode {
        let fallback = CGKeyCode(kVK_ANSI_V)
        guard let source = TISCopyCurrentKeyboardLayoutInputSource()?.takeRetainedValue() else { return fallback }
        if let namePointer = TISGetInputSourceProperty(source, kTISPropertyLocalizedName) {
            let name = Unmanaged<CFString>.fromOpaque(namePointer).takeUnretainedValue() as String
            if name.contains("⌘") { return fallback }
        }
        guard let dataPointer = TISGetInputSourceProperty(source, kTISPropertyUnicodeKeyLayoutData) else { return fallback }
        let layoutData = Unmanaged<CFData>.fromOpaque(dataPointer).takeUnretainedValue() as Data
        let target = UniChar(("v" as Unicode.Scalar).value)
        return layoutData.withUnsafeBytes { raw -> CGKeyCode in
            guard let layout = raw.baseAddress?.assumingMemoryBound(to: UCKeyboardLayout.self) else { return fallback }
            for code in 0..<128 {
                var deadKeyState: UInt32 = 0
                var characters = [UniChar](repeating: 0, count: 4)
                var length = 0
                let status = UCKeyTranslate(
                    layout, UInt16(code), UInt16(kUCKeyActionDisplay), 0, UInt32(LMGetKbdType()),
                    OptionBits(kUCKeyTranslateNoDeadKeysBit), &deadKeyState, characters.count, &length, &characters
                )
                if status == noErr, length == 1, characters[0] == target { return CGKeyCode(code) }
            }
            return fallback
        }
    }
}
